'use strict';
const W=1200,H=780,CELL=8,COLS=W/CELL,ROWS=Math.ceil(H/CELL),N=COLS*ROWS,MAX=600,STEP=.05;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function seedHash(str){let h=2166136261;for(let i=0;i<str.length;i++)h=Math.imul(h^str.charCodeAt(i),16777619);return h>>>0}
const SPECIES={
 herb:{name:'Herbivores',singular:'Herbivore',color:'#bcdca1',speed:16,life:180,cost:.72,adult:14,birth:.075,threshold:92,cooldown:22,role:'Broutent les plantes. Les sentinelles alertent le troupeau.',habitat:'land',initial:90},
 pred:{name:'Prédateurs',singular:'Prédateur',color:'#ec9e7f',speed:23,life:240,cost:1.02,adult:35,birth:.022,threshold:115,cooldown:65,role:'Chassent en meute et défendent un territoire.',habitat:'land',initial:12},
 bee:{name:'Pollinisateurs',singular:'Pollinisateur',color:'#efce72',speed:25,life:115,cost:.32,adult:12,birth:.045,threshold:92,cooldown:32,role:'Transportent le pollen et accélèrent la régénération des plantes.',habitat:'air',initial:30},
 scav:{name:'Charognards',singular:'Charognard',color:'#b7acd0',speed:22,life:240,cost:.34,adult:35,birth:.016,threshold:105,cooldown:70,role:'Consomment les carcasses et rendent une partie des nutriments au sol.',habitat:'air',initial:6},
 worm:{name:'Décomposeurs',singular:'Décomposeur',color:'#caac91',speed:6,life:140,cost:.17,adult:18,birth:.035,threshold:95,cooldown:40,role:'Transforment les débris organiques en fertilité locale.',habitat:'land',initial:24},
 fish:{name:'Poissons',singular:'Poisson',color:'#85c9dd',speed:18,life:160,cost:.32,adult:22,birth:.035,threshold:95,cooldown:40,role:'Consomment les algues. Le gel réduit leur activité.',habitat:'water',initial:32},
 frog:{name:'Amphibiens',singular:'Amphibien',color:'#8ccd89',speed:12,life:180,cost:.40,adult:25,birth:.028,threshold:100,cooldown:48,role:'Mangent insectes et algues. Relient milieux aquatiques et terrestres.',habitat:'both',initial:14}
};
const GENE_NAMES={speed:'Vitesse',vision:'Vision',life:'Longévité',size:'Taille',camo:'Camouflage',cold:'Résistance au froid',immunity:'Immunité'};
const defaults={temperature:18,rain:65,growth:1,fertility:75,reproduction:1,mutation:12,metabolism:1,aggression:1,wind:30,windDirection:45,social:1};
const controls=[['temperature','Température',-10,40,1,' °C','−10 °C','40 °C','env'],['rain','Précipitations',0,100,1,' %','Aride','Humide','env'],['growth','Croissance végétale',.1,3,.1,'×','Lente','Rapide','env'],['fertility','Fertilité des sols',10,100,1,' %','Pauvre','Riche','env'],['reproduction','Reproduction',.1,3,.1,'×','Rare','Fréquente','species'],['mutation','Taux de mutation',0,60,1,' %','Stable','Diversifié','species'],['metabolism','Dépense énergétique',.3,2,.1,'×','Faible','Élevée','species'],['aggression','Efficacité de chasse',.3,2,.1,'×','Faible','Élevée','species']];
const EVENT_NAMES={drought:'Sécheresse',rain:'Pluies',flood:'Crue',freeze:'Gel',fire:'Incendie',disease:'Épidémie',bloom:'Floraison',predators:'Prédateurs'};
class WorldEngine{
 constructor(seed='ASTER-42',preset='balanced',empty=false){
  this.s={version:2,seed,seedNum:seedHash(seed),rng:seedHash(seed),preset,day:0,tick:0,nextId:1,maxGen:1,params:{...defaults},seasons:true,animals:[],records:{},climate:null,births:0,deaths:0,extinct:{},packAlerts:{}};
  this.terrain=new Float32Array(N);this.plants=new Float32Array(N);this.forest=new Float32Array(N);this.nutrients=new Float32Array(N);this.pollen=new Float32Array(N);this.detritus=new Float32Array(N);this.fire=new Float32Array(N);this.barriers=new Uint8Array(N);
  this.history=[];this.events=[];this.land=[];this.water=[];this.version=0;this.lastSample=-1;this.counts={};this.grid=new Map();
  if(empty)return;
  if(preset==='harsh')Object.assign(this.s.params,{rain:35,fertility:50,temperature:28});
  if(preset==='paradise')Object.assign(this.s.params,{rain:80,growth:1.3});
  this.generateTerrain();
  for(let i=0;i<N;i++){this.plants[i]=this.terrain[i]>.43?.35+this.rnd()*.55:.1+this.rnd()*.15;this.nutrients[i]=.7;this.detritus[i]=this.terrain[i]>.43?this.rnd()*.15:0;this.pollen[i]=.2;}
  for(let [type,c] of Object.entries(SPECIES)){let n=c.initial;if(type==='herb')n=preset==='paradise'?120:preset==='harsh'?60:90;if(type==='pred')n=preset==='paradise'?0:preset==='harsh'?18:12;this.introduce(type,n,false);}
  this.log('Le monde prend vie. Sept rôles écologiques se rencontrent.');this.sample();
 }
 rnd(){let t=this.s.rng+=0x6D2B79F5;this.s.rng>>>=0;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296}
 hash(x,y){let n=Math.imul(x,374761393)+Math.imul(y,668265263)+this.s.seedNum;n=Math.imul(n^n>>>13,1274126177);return ((n^n>>>16)>>>0)/4294967295}
 noise(x,y){let ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy;fx=fx*fx*(3-2*fx);fy=fy*fy*(3-2*fy);return (this.hash(ix,iy)*(1-fx)+this.hash(ix+1,iy)*fx)*(1-fy)+(this.hash(ix,iy+1)*(1-fx)+this.hash(ix+1,iy+1)*fx)*fy}
 idx(x,y){return clamp(Math.floor(y/CELL),0,ROWS-1)*COLS+clamp(Math.floor(x/CELL),0,COLS-1)}
 point(i){return {x:(i%COLS+.5)*CELL,y:(Math.floor(i/COLS)+.5)*CELL}}
 baseHeight(x,y){let nx=x/COLS,ny=y/ROWS,ellipse=Math.hypot((nx-.5)/.55,(ny-.5)/.57),n=this.noise(x/22,y/22)*.24+this.noise(x/8,y/8)*.09+this.noise(x/3,y/3)*.025,riverX=.49+Math.sin(ny*8+1)*.13+Math.sin(ny*17)*.028;let h=.83-ellipse*.53+n-.15-Math.exp(-Math.pow((nx-riverX)/.032,2))*.34;if(this.s.preset==='islands')h-=.045+Math.max(0,.1-Math.abs(ny-.5))*.9;return h}
 generateTerrain(){for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){let i=y*COLS+x;this.terrain[i]=this.baseHeight(x,y);this.forest[i]=this.terrain[i]>.47&&this.noise(x/13+23,y/13+12)>.48?.8:0;}this.reindex();}
 reindex(){this.land=[];this.water=[];for(let i=0;i<N;i++){if(this.terrain[i]>.43&&this.terrain[i]<.8&&!this.barriers[i])this.land.push(i);else if(this.terrain[i]<=.43)this.water.push(i)}this.version++;}
 waterLevel(){return .43+(this.s.climate?.type==='flood'?.025+.045*this.s.climate.intensity:0)}
 allowed(x,y,type){if(x<8||x>W-8||y<8||y>H-8)return false;let c=SPECIES[type],i=this.idx(x,y),h=this.terrain[i];if(c.habitat==='air')return true;if(this.barriers[i]||h>.8)return false;let wet=h<=this.waterLevel();return c.habitat==='both'||(c.habitat==='water'?wet:!wet)}
 randomPoint(type){let list=SPECIES[type].habitat==='water'?this.water:this.land;for(let n=0;n<100;n++){let i=list[Math.floor(this.rnd()*list.length)];if(i===undefined)return null;let p=this.point(i);if(this.allowed(p.x,p.y,type))return p}return null}
 nearestHabitat(a,max=160){let best=null,score=Infinity;for(let r=8;r<=max;r+=16){for(let k=0;k<16;k++){let ang=k*Math.PI/8,x=a.x+Math.cos(ang)*r,y=a.y+Math.sin(ang)*r;if(this.allowed(x,y,a.type)){let d=r+this.hash(k,r)*.1;if(d<score){score=d;best={x,y}}}}if(best)return best}return null}
 createAnimal(type,parent=null,p=null){if(this.s.animals.length>=MAX)return null;p=p||this.randomPoint(type);if(!p)return null;let genes={};for(let key in GENE_NAMES)genes[key]=parent?clamp(parent.genes[key]*(1+(this.rnd()<this.s.params.mutation/100?(this.rnd()-.5)*.5:0)),.5,1.8):.85+this.rnd()*.3;let a={id:this.s.nextId++,type,x:p.x,y:p.y,angle:this.rnd()*Math.PI*2,energy:parent?58:75+this.rnd()*20,health:100*genes.size,age:parent?0:this.rnd()*25,generation:parent?parent.generation+1:1,parent:parent?.id||null,founder:parent?.founder||this.s.nextId-1,genes,cooldown:12+this.rnd()*20,think:0,tx:p.x,ty:p.y,state:'Explore',alive:true,home:parent?{...parent.home}:{...p},clan:parent?parent.clan:Math.floor(this.rnd()*4),memory:{food:null,danger:null},alarm:null,infection:0,immuneUntil:0,target:null,trail:[]};this.s.animals.push(a);this.s.records[a.id]={id:a.id,type,parent:a.parent,children:[],generation:a.generation,founder:a.founder,born:this.s.day,died:null,cause:null,genes:{...genes}};if(parent)this.s.records[parent.id].children.push(a.id);if(a.generation>this.s.maxGen){this.s.maxGen=a.generation;this.log('La génération '+a.generation+' vient de naître.')}return a}
 introduce(type,n,log=true){if(!SPECIES[type]||!Number.isInteger(n)||n<0||n>200)throw Error('Introduction invalide.');let count=0;for(let k=0;k<n&&this.s.animals.length<MAX;k++)if(this.createAnimal(type))count++;if(log)this.log(count+' '+SPECIES[type].name.toLowerCase()+' introduits.');return count}
 removeSpecies(type){let n=0;for(let a of this.s.animals)if(a.type===type){this.kill(a,'retrait',false);n++;}this.s.animals=this.s.animals.filter(a=>a.alive);this.log(n+' '+SPECIES[type].name.toLowerCase()+' retirés.');this.sample();return n}
 season(){return this.s.seasons?['Printemps','Été','Automne','Hiver'][Math.floor(this.s.day/60)%4]:'Climat constant'}
 climate(){let temp=this.s.params.temperature+(this.s.seasons?Math.sin(this.s.day/240*Math.PI*2)*9:0),rain=this.s.params.rain,c=this.s.climate;if(c){if(c.type==='drought'){temp+=10*c.intensity;rain*=Math.max(0,1-.92*c.intensity)}if(c.type==='rain'||c.type==='flood'){rain=100;temp-=3*c.intensity}if(c.type==='freeze')temp-=25*c.intensity}return {temp,rain}}
 log(text){this.events.unshift({day:Math.floor(this.s.day),text});this.events=this.events.slice(0,100)}
 event(type,intensity=1,duration=40,point=null){if(!EVENT_NAMES[type]||!Number.isFinite(intensity)||intensity<.2||intensity>2||!Number.isFinite(duration)||duration<5||duration>150)throw Error('Expérience invalide.');if(['drought','rain','freeze','flood'].includes(type)){this.s.climate={type,intensity,until:this.s.day+duration};this.version++;}else if(type==='fire'){let p=point||this.randomPoint('herb');if(p)this.paint('fire',p.x,p.y,16+intensity*18,intensity);this.s.fireUntil=this.s.day+duration;this.s.fireIntensity=intensity;}else if(type==='disease'){let eligible=this.s.animals.filter(a=>a.type!=='worm'&&a.immuneUntil<this.s.day);let count=Math.min(eligible.length,Math.ceil(5*intensity));for(let i=0;i<count;i++){let a=eligible.splice(Math.floor(this.rnd()*eligible.length),1)[0];a.infection=duration;}this.s.diseaseIntensity=intensity;}else if(type==='predators')this.introduce('pred',Math.round(8*intensity),false);else if(type==='bloom')for(let i of this.land)this.plants[i]=clamp(this.plants[i]+.4*intensity,0,1);this.log(EVENT_NAMES[type]+' déclenché'+(['predators','bloom'].includes(type)?'.':' · intensité '+intensity+' · '+duration+' jours.'));this.sample()}
 paint(tool,x,y,radius,intensity=1){let changed=0,terr=false;for(let yy=Math.max(0,Math.floor((y-radius)/CELL));yy<=Math.min(ROWS-1,Math.floor((y+radius)/CELL));yy++)for(let xx=Math.max(0,Math.floor((x-radius)/CELL));xx<=Math.min(COLS-1,Math.floor((x+radius)/CELL));xx++){let i=yy*COLS+xx,p=this.point(i);if(dist(p,{x,y})>radius)continue;changed++;if(tool==='forest'){if(this.terrain[i]>.43){this.forest[i]=1;this.plants[i]=Math.max(this.plants[i],.85)}}if(tool==='water'){this.terrain[i]=.33;this.forest[i]=0;this.barriers[i]=0;this.plants[i]=Math.min(.3,this.plants[i]);terr=true}if(tool==='mountain'){this.terrain[i]=.9;this.forest[i]=0;this.barriers[i]=0;terr=true}if(tool==='barrier'){this.barriers[i]=1;terr=true}if(tool==='bridge'){this.terrain[i]=.53;this.barriers[i]=0;this.plants[i]=Math.max(.25,this.plants[i]);terr=true}if(tool==='erase'){this.terrain[i]=this.baseHeight(xx,yy);this.barriers[i]=0;this.forest[i]=this.terrain[i]>.47&&this.noise(xx/13+23,yy/13+12)>.48?.8:0;this.fire[i]=0;terr=true}if(tool==='fire'&&this.terrain[i]>.43&&this.plants[i]>.1)this.fire[i]=clamp(.8*intensity,0,1)}if(terr)this.reindex();else this.version++;return changed}
 buildGrid(){this.grid=new Map;for(let a of this.s.animals){let key=Math.floor(a.x/80)+','+Math.floor(a.y/80);if(!this.grid.has(key))this.grid.set(key,[]);this.grid.get(key).push(a)}}
 nearby(a,r){let found=[],gx=Math.floor(a.x/80),gy=Math.floor(a.y/80),n=Math.ceil(r/80);for(let y=gy-n;y<=gy+n;y++)for(let x=gx-n;x<=gx+n;x++){let arr=this.grid.get(x+','+y);if(arr)for(let b of arr)if(b!==a&&b.alive&&dist(a,b)<r)found.push(b)}return found}
 wander(a,home=false){let origin=home?a.home:a;for(let k=0;k<12;k++){let ang=this.rnd()*Math.PI*2,r=25+this.rnd()*85,x=origin.x+Math.cos(ang)*r,y=origin.y+Math.sin(ang)*r;if(this.allowed(x,y,a.type)){a.tx=x;a.ty=y;return}}a.tx=a.x;a.ty=a.y}
 seekField(a,field,r=90){let best=null,bestV=field[this.idx(a.x,a.y)]-.03;for(let k=0;k<14;k++){let angle=this.rnd()*Math.PI*2,range=8+this.rnd()*r,x=a.x+Math.cos(angle)*range,y=a.y+Math.sin(angle)*range;if(!this.allowed(x,y,a.type))continue;let i=this.idx(x,y),v=field[i]-.00035*range;if(this.fire[i])continue;if(v>bestV){best={x,y};bestV=v}}return best}
 think(a){let c=SPECIES[a.type],i=this.idx(a.x,a.y),social=this.s.params.social>0,close=this.nearby(a,(a.type==='pred'?140:95)*a.genes.vision*(a.type==='herb'&&a.id%7===0?1.35:1));
  if(!this.allowed(a.x,a.y,a.type)){let refuge=this.nearestHabitat(a);if(refuge){a.tx=refuge.x;a.ty=refuge.y}a.state='Cherche un refuge';return}
  if(this.fire[i]>.01||this.fire[this.idx(a.x+12,a.y)]>.1){let safe=this.seekField(a,this.plants,120);if(safe){a.tx=safe.x;a.ty=safe.y}else this.wander(a);a.state='Fuit le feu';return}
  let threat=['herb','frog'].includes(a.type)?close.filter(b=>b.type==='pred').sort((b,c)=>dist(a,b)-dist(a,c))[0]:null;
  if(threat){a.memory.danger={x:threat.x,y:threat.y,until:this.s.day+25};if(social&&a.type==='herb'&&a.id%7===0){for(let mate of close.filter(b=>b.type==='herb'))mate.alarm={x:threat.x,y:threat.y,until:this.s.day+3};a.state='Sentinelle : alerte'}else a.state='Fuit';let dx=a.x-threat.x,dy=a.y-threat.y,len=Math.hypot(dx,dy)||1;a.tx=a.x+dx/len*90;a.ty=a.y+dy/len*90;return}
  if(social&&a.alarm?.until>this.s.day){a.state='Suit l’alerte';let dx=a.x-a.alarm.x,dy=a.y-a.alarm.y,len=Math.hypot(dx,dy)||1;a.tx=a.x+dx/len*75;a.ty=a.y+dy/len*75;return}
  if(a.type==='pred'){
   let prey=close.filter(b=>['herb','frog'].includes(b.type)&&dist(a,b)<140*a.genes.vision/(.7+b.genes.camo*.45*this.forest[this.idx(b.x,b.y)])).sort((b,c)=>dist(a,b)-dist(a,c))[0];
   let shared=social?this.s.packAlerts[a.clan]:null;if(!prey&&shared?.until>this.s.day)prey=this.s.animals.find(b=>b.id===shared.target&&b.alive&&dist(a,b)<220);
   if(prey&&a.energy<112){a.target=prey.id;a.tx=prey.x;a.ty=prey.y;a.state=social?'Chasse en meute':'Chasse';if(social){this.s.packAlerts[a.clan]={target:prey.id,until:this.s.day+1};let mates=close.filter(b=>b.type==='pred'&&b.clan===a.clan);if(mates.some(b=>b.id<a.id)&&dist(a,prey)>22){let off=(a.id%2?1:-1)*.75,ang=prey.angle+off;a.tx+=Math.cos(ang)*17;a.ty+=Math.sin(ang)*17}}return}
   a.target=null;let intruder=social?close.find(b=>b.type==='pred'&&b.clan!==a.clan&&dist(b,a.home)<110):null;if(intruder&&a.energy>75){a.state='Défend son territoire';a.tx=intruder.x;a.ty=intruder.y;return}a.state=a.energy>95?'Retour au territoire':'Patrouille';if(dist(a,a.home)>155&&social){a.tx=a.home.x;a.ty=a.home.y}else if(dist(a,{x:a.tx,y:a.ty})<12||this.rnd()<.2)this.wander(a,social);return;
  }
  if(a.type==='frog'){let insect=close.find(b=>b.type==='bee'&&dist(a,b)<40);if(insect&&a.energy<100){a.target=insect.id;a.tx=insect.x;a.ty=insect.y;a.state='Chasse un insecte';return}a.target=null;}
  let field=['scav','worm'].includes(a.type)?this.detritus:this.plants,available=field[i],threshold=a.type==='bee'?.25:.1;
  if(available>threshold&&a.energy<112){a.tx=a.x;a.ty=a.y;a.state=a.type==='bee'?'Pollinise':a.type==='worm'?'Décompose':a.type==='scav'?'Nettoie une carcasse':'Se nourrit';a.memory.food={x:a.x,y:a.y,until:this.s.day+45};return}
  let best=this.seekField(a,field,90*a.genes.vision);if(best){a.tx=best.x;a.ty=best.y;a.state='Cherche à manger';}
  else if(a.memory.food?.until>this.s.day&&this.allowed(a.memory.food.x,a.memory.food.y,a.type)&&field[this.idx(a.memory.food.x,a.memory.food.y)]>.12){a.tx=a.memory.food.x;a.ty=a.memory.food.y;a.state='Retrouve une ressource';}
  else if(social&&a.type==='herb'){let mates=close.filter(b=>b.type==='herb'&&b.clan===a.clan);if(mates.length&&a.energy>48){let center={x:mates.reduce((s,b)=>s+b.x,0)/mates.length,y:mates.reduce((s,b)=>s+b.y,0)/mates.length};if(dist(a,center)>25&&this.allowed(center.x,center.y,a.type)){a.tx=center.x;a.ty=center.y;a.state='Rejoint le troupeau';return}}this.wander(a);a.state=a.id%7===0?'Sentinelle : veille':'Explore';}
  else{this.wander(a);a.state='Explore';}
  if(a.memory.danger?.until>this.s.day&&dist({x:a.tx,y:a.ty},a.memory.danger)<65){this.wander(a,true);a.state='Évite un danger mémorisé';}
 }
 ecology(dt){let c=this.climate(),moisture=c.rain/100,tempFactor=Math.exp(-Math.pow((c.temp-22)/22,2)),rate=.009*this.s.params.growth*tempFactor*(.1+moisture*1.4),newFires=[];let wind=this.s.params.wind/100,angle=this.s.params.windDirection*Math.PI/180;
  for(let i=0;i<N;i++){let wet=this.terrain[i]<=this.waterLevel();this.pollen[i]=Math.max(0,this.pollen[i]-dt*.006);this.nutrients[i]=clamp(this.nutrients[i]-dt*.0003,0,2);if(wet){this.plants[i]=clamp(this.plants[i]+dt*.009*tempFactor*(.5-this.plants[i]),0,1);this.fire[i]=0;continue}if(this.terrain[i]>.8||this.barriers[i])continue;
   let cap=clamp(this.s.params.fertility/100*(.5+this.nutrients[i]*.6),.05,1),growth=rate*(.6+this.pollen[i]*1.15)*(cap-this.plants[i]);this.plants[i]=clamp(this.plants[i]+dt*(growth-.009*(1-moisture)*(1-tempFactor*.7)*this.plants[i]),0,1);this.detritus[i]=clamp(this.detritus[i]+dt*this.plants[i]*.0007,0,3);
   // Fallback microbial decay remains slow: worms and scavengers accelerate it.
   let decay=Math.min(this.detritus[i],dt*.001);this.detritus[i]-=decay;this.nutrients[i]=Math.min(2,this.nutrients[i]+decay*.5);
   if(this.fire[i]>.001){let burn=Math.min(this.plants[i],dt*.13*this.fire[i]);this.plants[i]-=burn;this.forest[i]=Math.max(0,this.forest[i]-burn*.75);this.nutrients[i]=Math.min(2,this.nutrients[i]+burn*.6);this.fire[i]=Math.max(0,this.fire[i]-dt*(.04+moisture*.14+(this.plants[i]<.08?.8:0)+(this.s.day>(this.s.fireUntil||0)?.7:0)));
    if(this.s.day<(this.s.fireUntil||0))for(let [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let x=i%COLS+dx,y=Math.floor(i/COLS)+dy,j=y*COLS+x;if(x<0||x>=COLS||y<0||y>=ROWS||this.terrain[j]<=this.waterLevel()||this.barriers[j]||this.plants[j]<.14||this.fire[j]>.01)continue;let align=dx*Math.cos(angle)+dy*Math.sin(angle),chance=dt*.45*(1-moisture*.85)*(1+wind*align)*this.fire[i]*(this.s.fireIntensity||1);if(this.rnd()<chance)newFires.push(j)}
   }else if(this.forest[i]<.8&&this.plants[i]>.55&&this.hash(i,781)>.65)this.forest[i]=Math.min(.8,this.forest[i]+dt*.0015);
  }for(let i of newFires)this.fire[i]=.9;
 }
 step(dt=STEP){this.s.tick++;this.s.day=this.s.tick*STEP;let c=this.climate();if(this.s.climate&&this.s.day>=this.s.climate.until){this.s.climate=null;this.version++;this.log('Fin de l’événement climatique.');c=this.climate()}if(this.s.tick%5===0)this.ecology(dt*5);this.buildGrid();let babies=[];
  for(let a of this.s.animals){if(!a.alive)continue;let cfg=SPECIES[a.type],i=this.idx(a.x,a.y);a.age+=dt;a.cooldown-=dt;a.think-=dt;if(a.think<=0){a.think=.3+this.rnd()*.2;this.think(a)}let fleeing=/Fuit|alerte|Alerte/.test(a.state),feeding=/nourrit|Pollinise|Décompose|Nettoie/.test(a.state),move=fleeing?1.45:feeding?.05:/Chasse/.test(a.state)?1.12:1;
   let velocity=cfg.speed*a.genes.speed/Math.sqrt(a.genes.size)*move;if(c.temp<0&&a.type==='fish')velocity*=.3;let dx=a.tx-a.x,dy=a.ty-a.y,len=Math.hypot(dx,dy),stranded=!this.allowed(a.x,a.y,a.type);
   if(len>2){let angle=Math.atan2(dy,dx),good=false;for(let off of [0,Math.PI/3,-Math.PI/3,Math.PI/2,-Math.PI/2,Math.PI]){let nx=a.x+Math.cos(angle+off)*velocity*dt,ny=a.y+Math.sin(angle+off)*velocity*dt;let escaping=stranded&&nx>8&&nx<W-8&&ny>8&&ny<H-8&&!this.barriers[this.idx(nx,ny)]&&this.terrain[this.idx(nx,ny)]<.8;if(this.allowed(nx,ny,a.type)||escaping){a.x=nx;a.y=ny;a.angle=angle+off;good=true;break}}if(!good)this.wander(a)}
   i=this.idx(a.x,a.y);let coldCost=1+Math.max(0,8-c.temp)/(18*a.genes.cold)+Math.max(0,c.temp-30)*a.genes.cold*.025,metabolic=cfg.cost*this.s.params.metabolism*(.62+.38*a.genes.speed*move)*Math.pow(a.genes.size,1.18)*coldCost*(.95+.07*a.genes.camo);
   a.energy-=dt*metabolic;if(stranded&&cfg.habitat!=='air')a.health-=dt*(a.type==='fish'?8:4);if(this.fire[i]>.02&&cfg.habitat!=='air')a.health-=dt*this.fire[i]*30;
   if(!fleeing){if(a.type==='herb'){let meal=Math.min(this.plants[i],dt*.30);this.plants[i]-=meal;a.energy+=meal*17;this.detritus[i]=Math.min(3,this.detritus[i]+meal*.025)}if(a.type==='bee'&&this.terrain[i]>.43&&this.plants[i]>.2){a.energy+=dt*1.2;this.pollen[i]=Math.min(1,this.pollen[i]+dt*.8);for(let j of [i-1,i+1,i-COLS,i+COLS])if(j>=0&&j<N)this.pollen[j]=Math.min(1,this.pollen[j]+dt*.4)}if(['scav','worm'].includes(a.type)){let meal=Math.min(this.detritus[i],dt*(a.type==='worm'?.08:.15));this.detritus[i]-=meal;a.energy+=meal*24;this.nutrients[i]=Math.min(2,this.nutrients[i]+meal*(a.type==='worm'?1.5:.6))}if(a.type==='fish'||a.type==='frog'&&this.terrain[i]<=this.waterLevel()){let meal=Math.min(this.plants[i],dt*.055);this.plants[i]-=meal;a.energy+=meal*23}}
   if((a.type==='pred'||a.type==='frog')&&a.target){let prey=this.nearby(a,11+3*a.genes.size).find(b=>b.id===a.target);if(prey){let damage=dt*(a.type==='pred'?42:60)*this.s.params.aggression*a.genes.size;prey.health-=damage;a.energy-=dt*.35;if(prey.health<=0){this.kill(prey,'prédation');a.energy+=a.type==='pred'?60:35;this.detritus[this.idx(prey.x,prey.y)]*=.35;a.target=null}}}
   if(a.state==='Défend son territoire'){let intruder=this.nearby(a,12).find(b=>b.type==='pred'&&b.clan!==a.clan);if(intruder){intruder.energy-=dt*.9;intruder.memory.danger={x:a.x,y:a.y,until:this.s.day+10};intruder.tx=intruder.home.x;intruder.ty=intruder.home.y}}
   if(a.infection>0){a.infection=Math.max(0,a.infection-dt);a.energy-=dt*.6*(this.s.diseaseIntensity||1)/a.genes.immunity;a.health-=dt*.4*(this.s.diseaseIntensity||1)/a.genes.immunity;if(this.s.tick%10===0)for(let b of this.nearby(a,20))if(b.type===a.type&&b.infection===0&&b.immuneUntil<this.s.day&&this.rnd()<.12*(this.s.diseaseIntensity||1)/b.genes.immunity)b.infection=25;if(a.infection===0)a.immuneUntil=this.s.day+80;}else if(a.energy>65)a.health=Math.min(100*a.genes.size,a.health+dt*.8);
   a.energy=clamp(a.energy,-10,a.type==='pred'?135:120);if(a.age>cfg.adult&&a.energy>cfg.threshold&&a.cooldown<=0&&a.infection===0&&this.s.animals.length+babies.length<MAX&&this.rnd()<dt*cfg.birth*this.s.params.reproduction){a.energy-=a.type==='pred'?65:32;a.cooldown=cfg.cooldown;babies.push(a)}if(a.health<=0||a.energy<=0||a.age>cfg.life*a.genes.life)this.kill(a,a.age>cfg.life*a.genes.life?'vieillesse':a.energy<=0?'faim':a.infection>0?'maladie':this.fire[i]>.01?'incendie':'blessure ou habitat');
  }this.s.animals=this.s.animals.filter(a=>a.alive);for(let a of babies)if(a.alive&&this.createAnimal(a.type,a,{x:a.x,y:a.y}))this.s.births++;if(Math.floor(this.s.day)!==this.lastSample)this.sample();
 }
 kill(a,cause,organic=true){if(!a.alive)return;a.alive=false;this.s.deaths++;let r=this.s.records[a.id];if(r){r.died=this.s.day;r.cause=cause}if(organic){let i=this.idx(a.x,a.y);this.detritus[i]=Math.min(3,this.detritus[i]+.7*a.genes.size);}}
 sample(){this.lastSample=Math.floor(this.s.day);let counts=Object.fromEntries(Object.keys(SPECIES).map(k=>[k,0]));for(let a of this.s.animals)counts[a.type]++;this.counts=counts;let mean=(type,key)=>{let arr=this.s.animals.filter(a=>!type||a.type===type);return arr.length?arr.reduce((s,a)=>s+a.genes[key],0)/arr.length:0};let data={day:this.s.day,...counts,plants:this.land.length?this.land.reduce((s,i)=>s+this.plants[i],0)/this.land.length*100:0,gen:this.s.maxGen,herbSpeed:mean('herb','speed'),predSpeed:mean('pred','speed'),vision:mean(null,'vision'),temp:this.climate().temp,rain:this.climate().rain,births:this.s.births,deaths:this.s.deaths,infected:this.s.animals.filter(a=>a.infection>0).length,burning:Array.from(this.fire).filter(x=>x>.01).length,diversity:Object.values(counts).filter(n=>n>0).length};if(this.history.at(-1)?.day===data.day)this.history[this.history.length-1]=data;else this.history.push(data);if(this.history.length>3000)this.history.shift();for(let type in counts){if(!counts[type]&&!this.s.extinct[type])this.log('Extinction : '+SPECIES[type].name.toLowerCase()+'.');this.s.extinct[type]=counts[type]===0}if(this.s.tick>0&&this.s.tick%1200===0&&this.s.seasons)this.log(this.season()+' : une nouvelle saison commence.');return data}
 snapshot(){return {s:structuredClone(this.s),layers:Object.fromEntries(['terrain','plants','forest','nutrients','pollen','detritus','fire','barriers'].map(k=>[k,Array.from(this[k])])),history:structuredClone(this.history),events:structuredClone(this.events),lastSample:this.lastSample}}
 static restore(raw){validateSnapshot(raw);let w=new WorldEngine(raw.s.seed,raw.s.preset,true);w.s=structuredClone(raw.s);for(let k of ['terrain','plants','forest','nutrients','pollen','detritus','fire','barriers'])w[k]=k==='barriers'?Uint8Array.from(raw.layers[k]):Float32Array.from(raw.layers[k]);w.history=structuredClone(raw.history);w.events=structuredClone(raw.events);w.lastSample=raw.lastSample;w.reindex();w.counts=Object.fromEntries(Object.keys(SPECIES).map(k=>[k,w.s.animals.filter(a=>a.type===k).length]));return w}
}
function validateSnapshot(v){const fail=()=>{throw Error('Sauvegarde invalide : le monde actuel a été conservé.')};if(!v||!v.s||!v.layers||!Array.isArray(v.history)||v.history.length>3000||!Array.isArray(v.events)||v.events.length>100)fail();let s=v.s;if(typeof s.seed!=='string'||s.seed.length>80||!['balanced','harsh','paradise','islands'].includes(s.preset)||!Number.isInteger(s.tick)||s.tick<0||!Number.isFinite(s.day)||Math.abs(s.day-s.tick*STEP)>1e-6||!Number.isInteger(s.rng)||s.rng<0||s.rng>4294967295||!Number.isInteger(s.seedNum)||!Array.isArray(s.animals)||s.animals.length>MAX||!s.records||typeof s.records!=='object'||!Number.isInteger(s.nextId)||typeof s.seasons!=='boolean'||!Number.isInteger(s.maxGen)||!Number.isFinite(s.births)||!Number.isFinite(s.deaths)||!s.extinct||!s.packAlerts)fail();for(let [k,,min,max] of controls)if(!Number.isFinite(s.params?.[k])||s.params[k]<min||s.params[k]>max)fail();for(let [k,min,max] of [['wind',0,100],['windDirection',0,360],['social',0,1]])if(!Number.isFinite(s.params[k])||s.params[k]<min||s.params[k]>max)fail();for(let k of ['terrain','plants','forest','nutrients','pollen','detritus','fire','barriers'])if(!Array.isArray(v.layers[k])||v.layers[k].length!==N||!v.layers[k].every(x=>Number.isFinite(x)&&x>=(k==='terrain'?-1:0)&&x<=(k==='detritus'?3:k==='nutrients'?2:1)))fail();let ids=new Set;
 for(let a of s.animals){if(!Number.isInteger(a.id)||a.id<1||ids.has(a.id)||!SPECIES[a.type]||!['x','y','angle','energy','health','age','generation','cooldown','think','tx','ty','clan','infection','immuneUntil','founder'].every(k=>Number.isFinite(a[k]))||a.x<0||a.x>W||a.y<0||a.y>H||!a.genes||!Object.keys(GENE_NAMES).every(k=>Number.isFinite(a.genes[k])&&a.genes[k]>=.5&&a.genes[k]<=1.8)||!Number.isInteger(a.clan)||a.clan<0||a.clan>3||!a.memory||!a.home||!Number.isFinite(a.home.x)||!Number.isFinite(a.home.y)||typeof a.state!=='string'||a.state.length>100||!s.records[a.id]||!Array.isArray(a.trail)||a.trail.length>60||!a.trail.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)))fail();for(let p of [a.memory.food,a.memory.danger,a.alarm])if(p&&(!Number.isFinite(p.x)||!Number.isFinite(p.y)||!Number.isFinite(p.until)))fail();ids.add(a.id)}if(s.nextId<=Math.max(0,...ids))fail();if(Object.keys(s.records).length>100000)fail();for(let [id,r] of Object.entries(s.records)){if(!r||!Number.isInteger(r.id)||r.id!=id||!SPECIES[r.type]||!Number.isInteger(r.generation)||!Number.isInteger(r.founder)||!(r.parent===null||Number.isInteger(r.parent))||!Array.isArray(r.children)||!r.children.every(Number.isInteger)||!Number.isFinite(r.born)||!(r.died===null||Number.isFinite(r.died))||!r.genes||!Object.keys(GENE_NAMES).every(k=>Number.isFinite(r.genes[k])&&r.genes[k]>=.5&&r.genes[k]<=1.8))fail()}if(!v.history.every(d=>d&&Object.values(d).every(Number.isFinite))||!v.events.every(e=>Number.isFinite(e.day)&&typeof e.text==='string'&&e.text.length<2000)||!Number.isFinite(v.lastSample))fail();if(s.climate&&(!['drought','rain','freeze','flood'].includes(s.climate.type)||!Number.isFinite(s.climate.until)||!Number.isFinite(s.climate.intensity)||s.climate.intensity<.2||s.climate.intensity>2))fail();for(let alert of Object.values(s.packAlerts))if(!Number.isInteger(alert.target)||!Number.isFinite(alert.until))fail();return v}
function migrateV1(v){if(v?.format!=='biosphere'||v.version!==1||!v.state||!Array.isArray(v.plants)||v.plants.length!==N)throw Error('Format de sauvegarde incompatible.');let old=v.state,w=new WorldEngine(old.seed,old.preset);w.s={...w.s,...structuredClone(old),version:2,tick:Math.round(old.day/STEP),day:Math.round(old.day/STEP)*STEP,params:{...defaults,...old.params},packAlerts:{}};for(let a of w.s.animals){a.genes={size:1,camo:1,cold:1,immunity:1,...a.genes};a.health=100*a.genes.size;a.home={x:a.x,y:a.y};a.memory={food:null,danger:null};a.alarm=null;a.infection=0;a.immuneUntil=0;a.clan=a.id%4;a.founder=a.id;a.trail=[];a.alive=true;}for(let r of Object.values(w.s.records)){r.genes=w.s.animals.find(a=>a.id===r.id)?.genes||Object.fromEntries(Object.keys(GENE_NAMES).map(k=>[k,1]));r.founder=r.id;r.cause=r.cause||null;}w.plants=Float32Array.from(v.plants);w.history=[];w.events=[];w.s.climate=w.s.climate?{...w.s.climate,intensity:1}:null;w.sample();w.log('Sauvegarde V1 adaptée au moteur V2. Les nouvelles espèces peuvent être introduites depuis le réseau vivant.');validateSnapshot(w.snapshot());return w}
