class WorldRenderer{
 constructor(canvas,getWorld,onSelect){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.getWorld=getWorld;this.onSelect=onSelect;this.camera={x:W/2,y:H/2,z:1};this.base=document.createElement('canvas');this.base.width=W;this.base.height=H;this.baseVersion=-1;this.baseWorld=null;this.transform={s:1,ox:0,oy:0};this.selected=null;this.follow=false;this.view='natural';this.trails=false;this.brush='observe';this.radius=30;this.hover=null;this.onPaint=null;this.onPaintStart=null;this.onPaintEnd=null;this.pointers=new Map;this.drag=null;this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas);this.bind();}
 resize(){let r=this.canvas.getBoundingClientRect();this.width=r.width;this.height=r.height;this.dpr=Math.min(window.devicePixelRatio||1,2);if(this.canvas.width!==Math.round(r.width*this.dpr)||this.canvas.height!==Math.round(r.height*this.dpr)){this.canvas.width=Math.round(r.width*this.dpr);this.canvas.height=Math.round(r.height*this.dpr)}}
 reset(){this.camera={x:W/2,y:H/2,z:1};this.follow=false}
 position(e){let r=this.canvas.getBoundingClientRect();return {x:(e.clientX-r.left-this.transform.ox)/this.transform.s,y:(e.clientY-r.top-this.transform.oy)/this.transform.s}}
 bind(){let canvas=this.canvas;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});let p=this.position(e);this.drag={x:e.clientX,y:e.clientY,cx:this.camera.x,cy:this.camera.y,moved:false,last:p,painting:this.brush!=='observe'};if(this.pointers.size===2){let q=[...this.pointers.values()];this.pinch={distance:Math.hypot(q[0].x-q[1].x,q[0].y-q[1].y),z:this.camera.z};this.drag.moved=true;this.drag.painting=false;}else if(this.drag.painting){this.onPaintStart?.();this.onPaint?.(p);}});canvas.addEventListener('pointermove',e=>{this.hover=this.position(e);if(!this.pointers.has(e.pointerId))return;this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pinch&&this.pointers.size===2){let p=[...this.pointers.values()];this.camera.z=clamp(this.pinch.z*Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)/this.pinch.distance,1,6);return}if(this.drag){let dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;if(Math.hypot(dx,dy)>4)this.drag.moved=true;if(this.drag.painting){let p=this.position(e),d=dist(p,this.drag.last),steps=Math.min(100,Math.ceil(d/Math.max(4,this.radius*.3)));for(let n=1;n<=steps;n++)this.onPaint?.({x:this.drag.last.x+(p.x-this.drag.last.x)*n/steps,y:this.drag.last.y+(p.y-this.drag.last.y)*n/steps});this.drag.last=p;}else if(this.drag.moved){this.follow=false;this.camera.x=this.drag.cx-dx/this.transform.s;this.camera.y=this.drag.cy-dy/this.transform.s;}}});canvas.addEventListener('pointerup',e=>{if(this.drag?.painting)this.onPaintEnd?.();else if(this.drag&&!this.drag.moved&&!this.pinch){let p=this.position(e),a=this.getWorld().s.animals.filter(a=>dist(a,p)<18/this.transform.s).sort((a,b)=>dist(a,p)-dist(b,p))[0];this.onSelect?.(a?.id||null);}this.pointers.delete(e.pointerId);if(!this.pointers.size){this.drag=null;this.pinch=null}});canvas.addEventListener('pointercancel',()=>{if(this.drag?.painting)this.onPaintEnd?.();this.pointers.clear();this.drag=null;this.pinch=null});canvas.addEventListener('pointerleave',()=>this.hover=null);canvas.addEventListener('wheel',e=>{e.preventDefault();let p=this.position(e),r=canvas.getBoundingClientRect();this.camera.z=clamp(this.camera.z*Math.exp(-e.deltaY*.001),1,6);let s=Math.min(this.width/W,this.height/H)*this.camera.z;this.camera.x=p.x-(e.clientX-r.left-this.width/2)/s;this.camera.y=p.y-(e.clientY-r.top-this.height/2)/s;this.follow=false},{passive:false});}
 terrain(w){let c=this.base.getContext('2d'),small=document.createElement('canvas');small.width=COLS;small.height=ROWS;let g=small.getContext('2d'),im=g.createImageData(COLS,ROWS);for(let i=0;i<N;i++){let h=w.terrain[i],col=h<=w.waterLevel()?(h>.40?[71,105,91]:[35,68,67]):h>.8?[138,142,125]:h<.47?[158,170,112]:[111,151,88];let grain=w.hash(i,921)*9,shade=(w.terrain[Math.min(N-1,i+1)]-h)*90;for(let k=0;k<3;k++)im.data[i*4+k]=clamp(col[k]+grain+shade,0,255);im.data[i*4+3]=255}g.putImageData(im,0,0);c.imageSmoothingEnabled=true;c.drawImage(small,0,0,W,H);
  for(let i=0;i<N;i++){let p=w.point(i);if(w.barriers[i]){c.fillStyle='#625f50';c.fillRect(p.x-4,p.y-5,8,7);c.strokeStyle='#a6a18b';c.lineWidth=.7;c.strokeRect(p.x-4,p.y-5,8,7);}else if(w.terrain[i]>.8&&w.hash(i,423)>.87){c.fillStyle='#c1c4ae';c.beginPath();c.moveTo(p.x-5,p.y+3);c.lineTo(p.x,p.y-5);c.lineTo(p.x+5,p.y+3);c.fill();}else if(w.terrain[i]>.43&&w.hash(i,59)>.65){c.strokeStyle='#bed09450';c.lineWidth=.7;c.beginPath();c.moveTo(p.x,p.y+2);c.lineTo(p.x-1,p.y-2);c.moveTo(p.x+2,p.y+3);c.lineTo(p.x+3,p.y);c.stroke()}}this.baseVersion=w.version;this.baseWorld=w;
 }
 draw(){let w=this.getWorld();if(!w||!this.width||!this.height)return;let g=this.ctx,sw=this.width,sh=this.height;g.setTransform(this.dpr,0,0,this.dpr,0,0);g.fillStyle='#23413e';g.fillRect(0,0,sw,sh);let followed=w.s.animals.find(a=>a.id===this.selected);if(this.follow&&followed){this.camera.x+=(followed.x-this.camera.x)*.1;this.camera.y+=(followed.y-this.camera.y)*.1}let s=Math.min(sw/W,sh/H)*this.camera.z;this.camera.x=clamp(this.camera.x,0,W);this.camera.y=clamp(this.camera.y,0,H);let ox=sw/2-this.camera.x*s,oy=sh/2-this.camera.y*s;this.transform={s,ox,oy};g.translate(ox,oy);g.scale(s,s);if(this.baseWorld!==w||this.baseVersion!==w.version)this.terrain(w);g.drawImage(this.base,0,0);let phase=w.s.day*.04;
  if(['food','fertility','pollination'].includes(this.view)){let field=this.view==='food'?w.plants:this.view==='fertility'?w.nutrients:w.pollen;for(let i=0;i<N;i++){if(w.terrain[i]<.43&&this.view!=='food')continue;let v=clamp(field[i],0,1);g.fillStyle=`rgba(${Math.round(190-v*110)},${Math.round(100+v*100)},70,.65)`;g.fillRect(i%COLS*CELL,Math.floor(i/COLS)*CELL,CELL,CELL)}}
  for(let n=0;n<130;n++){let x=w.hash(n,900)*W,y=w.hash(n,901)*H;if(w.terrain[w.idx(x,y)]<w.waterLevel()){g.strokeStyle='#cde6d516';g.lineWidth=.8;g.beginPath();g.moveTo(x+Math.sin(phase+n)*5,y);g.quadraticCurveTo(x+9,y+2,x+16,y);g.stroke()}}
  for(let i=0;i<N;i++){let x=(i%COLS+.5)*CELL,y=(Math.floor(i/COLS)+.5)*CELL;if(w.forest[i]>.2&&w.plants[i]>.18&&w.terrain[i]<.8&&w.terrain[i]>w.waterLevel()&&w.hash(i,22)>.76){let r=(3+w.hash(i,33)*5)*(.5+w.forest[i]*.5),sway=Math.sin(phase*3+x*.03)*.5;g.fillStyle='#173b2530';g.beginPath();g.ellipse(x+4,y+3,r*1.15,r*.6,-.3,0,7);g.fill();g.strokeStyle='#5f6945';g.lineWidth=1.4;g.beginPath();g.moveTo(x,y+4);g.lineTo(x,y-r);g.stroke();g.fillStyle=w.season()==='Automne'?'#858849':w.season()==='Hiver'?'#7c8c65':'#48723c';g.beginPath();g.ellipse(x+sway,y-r*.5,r,r*.75,0,0,7);g.fill();g.fillStyle=w.season()==='Automne'?'#b1a862':'#86a65b';g.beginPath();g.ellipse(x-1+sway,y-r*.85,r*.7,r*.55,0,0,7);g.fill();}if(w.detritus[i]>.4&&w.terrain[i]>w.waterLevel()){g.fillStyle='#6b554550';g.beginPath();g.ellipse(x,y,3+w.detritus[i],2,0,0,7);g.fill()}if(w.fire[i]>.015){let h=8+w.fire[i]*14,j=Math.sin(phase*24+i)*3;g.fillStyle='#ec742bc4';g.beginPath();g.moveTo(x-4,y+3);g.quadraticCurveTo(x-7,y-h*.4,x+j,y-h);g.quadraticCurveTo(x+8,y-h*.3,x+4,y+3);g.fill();g.fillStyle='#ffdb80d0';g.beginPath();g.ellipse(x,y-1,2,h*.26,0,0,7);g.fill();}}
  if(this.view==='social'){let seen=new Set;for(let a of w.s.animals){if(a.type==='pred'&&!seen.has(a.clan)){seen.add(a.clan);g.strokeStyle=['#ebb19050','#b2d98850','#a9bde050','#dda8d750'][a.clan];g.lineWidth=2;g.setLineDash([6,5]);g.beginPath();g.arc(a.home.x,a.home.y,145,0,7);g.stroke();g.setLineDash([])}if(a.memory.food){g.strokeStyle='#ddf59c25';g.beginPath();g.moveTo(a.x,a.y);g.lineTo(a.memory.food.x,a.memory.food.y);g.stroke()}}}
  for(let a of w.s.animals){if((this.trails||a.id===this.selected)&&a.trail.length>1){g.strokeStyle=SPECIES[a.type].color+'65';g.lineWidth=1;g.beginPath();a.trail.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.lineTo(a.x,a.y);g.stroke()}this.animal(g,a,w);}
  if(followed){g.strokeStyle='#eeffca';g.lineWidth=1.4/s;g.setLineDash([4/s,3/s]);g.beginPath();g.arc(followed.x,followed.y,13*followed.genes.size,0,7);g.stroke();g.setLineDash([]);g.fillStyle='#172c21';g.font=`${12/s}px sans-serif`;g.textAlign='center';g.fillText('#'+followed.id,followed.x,followed.y-21/s)}
  if(w.s.climate?.type==='rain'||w.s.climate?.type==='flood'){g.strokeStyle='#d6e6d448';g.lineWidth=.8;g.beginPath();for(let n=0;n<90;n++){let x=(w.hash(n,99)*W+w.s.day*10)%W,y=(w.hash(n,98)*H+w.s.day*55)%H;g.moveTo(x,y);g.lineTo(x-4,y+13)}g.stroke()}
  if(this.brush!=='observe'&&this.hover){g.strokeStyle='#f1f6d6';g.fillStyle='#e8f8c51a';g.lineWidth=1.5/s;g.beginPath();g.arc(this.hover.x,this.hover.y,this.radius,0,7);g.fill();g.stroke();}
  g.setTransform(this.dpr,0,0,this.dpr,0,0);if(w.s.climate?.type==='freeze'){g.fillStyle='#cae8ff2b';g.fillRect(0,0,sw,sh)}if(w.s.climate?.type==='drought'){g.fillStyle='#efb83216';g.fillRect(0,0,sw,sh)}
 }
 animal(g,a,w){let type=a.type,size=a.genes.size*(.65+Math.min(.35,a.age/60)),color=SPECIES[type].color;if(type==='herb')color=`hsl(${65+a.genes.camo*20},${27+a.genes.camo*7}%,${82-a.genes.camo*13}%)`;if(type==='pred')color=`hsl(${18+a.genes.camo*8},45%,${77-a.genes.camo*12}%)`;if(this.view==='energy')color=`hsl(${clamp(a.energy,0,120)},70%,65%)`;if(this.view==='genes')color=`hsl(${(a.generation*43+80)%360},70%,68%)`;g.save();g.translate(a.x,a.y);g.rotate(a.angle);g.scale(size,size);g.fillStyle='#13261d35';g.beginPath();g.ellipse(1,2,7,3,0,0,7);g.fill();g.fillStyle=color;g.strokeStyle=color;g.lineWidth=1.5;
  if(type==='bee'){g.fillStyle='#f6ffe58c';g.beginPath();g.ellipse(0,-2,4,2,Math.sin(w.s.day*22)*.5,0,7);g.ellipse(0,2,4,2,-Math.sin(w.s.day*22)*.5,0,7);g.fill();g.fillStyle=color;g.beginPath();g.ellipse(0,0,3.5,1.7,0,0,7);g.fill();g.strokeStyle='#5c5739';g.beginPath();g.moveTo(-1,-1);g.lineTo(-1,1);g.stroke();}
  else if(type==='scav'){g.beginPath();g.ellipse(0,0,5,2.5,0,0,7);g.fill();let flap=Math.sin(w.s.day*8+a.id)*2;g.beginPath();g.moveTo(2,0);g.lineTo(-3,-8-flap);g.lineTo(-1,0);g.lineTo(-3,8+flap);g.closePath();g.fill();}
  else if(type==='fish'){g.beginPath();g.ellipse(0,0,5,2.3,0,0,7);g.fill();g.beginPath();g.moveTo(-4,0);g.lineTo(-8,-3);g.lineTo(-8,3);g.closePath();g.fill();}
  else if(type==='worm'){g.lineWidth=2.4;g.beginPath();g.moveTo(-5,0);g.quadraticCurveTo(0,Math.sin(w.s.day*5+a.id)*3,5,0);g.stroke();}
  else if(type==='frog'){g.beginPath();g.ellipse(0,0,4,3,0,0,7);g.fill();g.beginPath();g.moveTo(-2,-2);g.lineTo(-6,-5);g.lineTo(-7,-2);g.moveTo(-2,2);g.lineTo(-6,5);g.lineTo(-7,2);g.stroke();}
  else{g.beginPath();g.ellipse(0,0,5.5,3,0,0,7);g.fill();let stride=Math.sin(w.s.day*17+a.id)*2;g.beginPath();g.moveTo(-3,-2);g.lineTo(-5+stride,-4);g.moveTo(3,2);g.lineTo(1-stride,4);g.stroke();if(type==='pred'){g.beginPath();g.moveTo(-4,0);g.lineTo(-11,-2);g.lineTo(-9,2);g.closePath();g.fill();g.beginPath();g.moveTo(4,-3);g.lineTo(10,0);g.lineTo(4,3);g.closePath();g.fill();g.beginPath();g.moveTo(4,-1);g.lineTo(4,-5);g.lineTo(7,-2);g.fill();}else{g.beginPath();g.ellipse(5,0,3,2.4,0,0,7);g.fill();g.beginPath();g.moveTo(5,-1);g.lineTo(1,-5);g.moveTo(6,0);g.lineTo(4,-5);g.stroke();}}
  if(type!=='worm'){g.fillStyle='#27392c';g.beginPath();g.arc(type==='herb'||type==='pred'?6:3,-.8,.6,0,7);g.fill()}g.restore();if(a.infection>0){g.strokeStyle='#e5a5d4';g.lineWidth=1;g.beginPath();g.arc(a.x,a.y,8*size,0,7);g.stroke()}if(a.type==='herb'&&a.id%7===0&&this.view==='social'){g.fillStyle='#edf29e';g.beginPath();g.arc(a.x,a.y-11,2.5,0,7);g.fill()}
 }
 destroy(){this.resizeObserver.disconnect()}
}
